### PR TITLE
fix tooltip

### LINKED ISSUE #15: Tooltips only seem to work on small screens
## Scope

> The tooltip is not visible if the page is wider than about 1000px (Firefox/Chrome on Win):

image

## Deliverable

- Understand why this is happening
- Submit fix as PR

## Time estimate

- 1h

### PR DESCRIPTION
**Pull request by il3ven**
Fixes #15

### CODE REVIEW

**Comment by d80ep08th** [comment]
Is deleting the entire condition that makes the tooltip appear on screens of size 1024px or less the best way? 
Im asking for my own wisdom because I figured out that the tooltip starts appearing right after 1168px point , which is like 144px more.

**Comment by il3ven** [comment]
> Im asking for my own wisdom because I figured out that the tooltip starts appearing right after 1168px point , which is like 144px more.

For me the tooltip stops appearing as soon as the size increases to more than 1024px. It is not visible at 1025px.

> Is deleting the entire condition that makes the tooltip appear on screens of size 1024px or less the best way?

I don't see any problem.

**Comment by d80ep08th** [comment]
> I don't see any problem.
I dont find the css readable at all but @TimDaub must have had  a good reason for embedding "@media (max-width: 1024px) "  in the first place, unless it was supposed to be a good first issue lol

**Comment by TimDaub** [comment]
the provenance for why I ended up using that mediaquery is this PR: https://github.com/emareg/classlesscss/pull/9/files

If I remember correctly, then this was the first proposal where the media query was used: https://github.com/emareg/classlesscss/issues/8#issuecomment-842251290

And the reason provided was to: 

> Since the title tooltip **is not enabled on mobile devices**,

Now, I wonder if it even makes sense continuing to fix this. On the classless repo, I've asked if it may make sense to use an entirely different concept of showing additional information that would also work on mobile devices properly: https://github.com/emareg/classlesscss/issues/11

**Comment by TimDaub** [comment]
I'll accept this fix for now, but for the long term, I think we should go towards the direction outlined here: https://github.com/rugpullindex/design-system/pull/25

**Comment by il3ven** [comment]
I agree that tooltip is not the best solution needs to replaced with something else.

___

> Since the title tooltip is not enabled on mobile devices,

If this was the reason then I guess the code should have been this.

```diff
- @media (max-width:1024px)
+ @media (min-width:1024px)
```

**Pull request merged**
